- hosts: localhost
  gather_facts: false
  name: NFS Configuration
  vars:
    login: &login
     hostname: "{{ clusterip }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     https: "{{ https_option }}"
     validate_certs: "{{ validate_certs_option }}"
  vars_files:
  - variables.yml
  tasks:
  - name: Create Volume
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      aggregate_name: "{{ aggr }}"
      size: "{{ vol_size }}"
      size_unit: gb
      space_guarantee: none
      policy: "{{ export_policy }}"
      percent_snapshot_space: 0
      vserver: "{{ svm_name }}"
      volume_security_style: unix    
      wait_for_completion: true
      junction_path: "{{ '/' + vol_name }}"
      <<: *login
  - name: Create ExportPolicyRule
    na_ontap_export_policy_rule:
     state: present
     name: "{{ export_policy }}"
     vserver: "{{ svm_name }}"
     client_match: "{{ client_match }}"
     ro_rule: sys
     rw_rule: sys
     protocol: nfs,nfs3
     super_user_security: sys
     allow_suid: true
     <<: *login

  