- hosts: localhost
  gather_facts: false
  name: Configure Cifs 
  vars:
    login: &login
     hostname: "{{ clusterip }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     https: "{{ https_option }}"
     validate_certs: "{{ validate_certs_option }}"
  vars_files:
  - variables.yml
  tasks:
  - name: Create Volume
    na_ontap_volume:
      state: present
      name: "{{ cifs_vol }}"
      aggregate_name: "{{ aggr }}"
      size: "{{ vol_size }}"
      size_unit: gb
      space_guarantee: none
      policy: "{{ export_policy }}"
      percent_snapshot_space: 0
      vserver: "{{ svm_name }}"
      volume_security_style: ntfs    
      wait_for_completion: true
      junction_path: "{{ '/' + cifs_vol }}"
      <<: *login
  
  - name: Create cifs_server
    na_ontap_cifs_server:
     state: present
     vserver: "{{ svm_name }}"
     cifs_server_name: cifs_server
     workgroup: workgroup
     <<: *login
  
  - name: Create CIFS share
    na_ontap_cifs:
      state: present
      share_name: "{{ share_name }}"
      path: "{{ '/' + cifs_vol }}"
      vserver: "{{ svm_name }}"
      share_properties: browsable,oplocks
      symlink_properties: read_only,enable
      <<: *login
  - name: Create CIFS share acl
    na_ontap_cifs_acl:
     state: present
     vserver: "{{ svm_name }}"
     share_name: "{{ share_name }}"
     user_or_group: Everyone
     permission: change
     <<: *login