- hosts: localhost
  gather_facts: false
  name: Decommission
  vars:
    login: &login
     hostname: "{{ clusterip }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     https: "{{ https_option }}"
     validate_certs: "{{ validate_certs_option }}"
  vars_files:
  - variables.yml
  tasks:
  - name: Delete ExportPolicyRule
    na_ontap_export_policy_rule:
     state: absent
     name: "{{ export_policy }}"
     vserver: "{{ svm_name }}"
     client_match: "{{ client_match }}"
     <<: *login

  - name: Delete NFS Volume
    na_ontap_volume:
      state: absent
      name: "{{ vol_name }}"
      vserver: "{{ svm_name }}"
      size: "{{ vol_size }}"
      <<: *login